database:
  nome: loja_info_plus
  tabelas:

    vendas:
      nome: vendas
      colunas:
        venda_id: venda_id
        vendedor_id: vendedor_id
        produto_id: produto_id
        data_venda: data_venda
        quantidade: quantidade
        valor_compra: valor_compra
        valor_venda: valor_venda
        forma_pagamento: forma_pagamento
        desconto: desconto
        cidade: cidade
        estado: estado
        status: status

    produtos:
      nome: produtos
      colunas:
        produto_id: produto_id
        nome_produto: nome_produto
        categoria: categoria
        valor_compra: valor_compra
        valor_venda: valor_venda

    vendedores:
      nome: vendedores
      colunas:
        vendedor_id: vendedor_id
        nome_vendedor: nome_vendedor
