columns:
  venda_id: "venda_id"
  vendedor_id: "vendedor_id"
  produto_id: "produto_id"
  nome_vendedor: "nome_vendedor"
  nome_produto: "nome_produto"
  data_venda: "data_venda"
  quantidade: "quantidade"
  valor_compra: "valor_compra"
  valor_venda: "valor_venda"
  forma_pagamento: "forma_pagamento"
  categoria: "categoria"
  desconto: "desconto"
  cidade: "cidade"
  estado: "estado"
  status: "status"
